### ISSUE TITLE
Please im needing an inplementation of previousClearBit and previousSetBit

### ISSUE THREAD

**Issue by jabolinux** [brettwooldridge/SparseBitSet#11]
Hello

Could you please, implement the following two methods:

int | previousClearBit(int i)Returns the index of the last bit that is set to false that occurs on or before the specified ending index.
-- | --
int | previousSetBit(int i)Returns the index of the last bit that is set to true that occurs on or before the specified ending index.

Thanks a lot
Regards

**Comment by brettwooldridge** [comment]
@jabolinux Pull requests welcome.  😁

**Comment by lemire** [comment]
@brettwooldridge I approve this answer.

**Comment by lfbayer** [comment]
This has been implemented and released to maven as SparseBitSet-1.2. See #7
