### ISSUE TITLE
Request for previousSetBit and previousClearBit methods

### ISSUE THREAD

**Issue by mbjarland** [brettwooldridge/SparseBitSet#7]
The java BitSet implementation has these as: 

    int	previousClearBit(int fromIndex)
    int	previousSetBit(int fromIndex)

Many thanks for this excellent implementation. This is truly useful and a great addition to the JVM ecosystem of tools. 

I started looking at creating a pull request but given the complexity of the implementation I backed out and figured I would ask the implementor for help first. Let me know if this would be feasible and if so, whether this is something you could envision adding.

**Comment by lfbayer** [comment]
The SparseBitSet-1.2 maven artifact has been published containing this enhancement. Thanks for the code!
